# Generated by Django 5.2.3 on 2025-07-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_approvalstep_file_approvalstep_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='file',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='App.document'),
        ),
    ]
