# Generated by Django 5.2.3 on 2025-07-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_document_vacation_days_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='vacation_days_left',
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_days_left',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
