# Generated by Django 5.2.4 on 2025-07-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_group_subject_remove_schedule_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(default='10:00'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(default='10:00'),
        ),
    ]
