# Generated by Django 5.2.4 on 2025-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_product_redeem_delete_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='code',
            field=models.CharField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
