# Generated by Django 5.2.3 on 2025-07-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_report_status_alter_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
