# Generated by Django 5.2.3 on 2025-08-02 12:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='user_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('computer', 'Computer is broken'), ('light', 'Light Issue'), ('water', 'Water/plumbing'), ('internet', 'Wifi/Internet'), ('heating', 'Heating/Cooling'), ('other', 'Other')], max_length=50),
        ),
    ]
