# Generated by Django 5.2.3 on 2025-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_sendcode_remove_approvalstep_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
