# Generated by Django 5.2.3 on 2025-07-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_sendcode_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vacation_days_left',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
