# Generated by Django 5.2.4 on 2025-07-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_business_math_phylosophy_physics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='business_doc/'),
        ),
        migrations.AlterField(
            model_name='math',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='math_doc/'),
        ),
        migrations.AlterField(
            model_name='phylosophy',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='phylosophy_doc/'),
        ),
        migrations.AlterField(
            model_name='physics',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='physics_doc/'),
        ),
    ]
