# Generated by Django 5.2.3 on 2025-07-26 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_redeem_code_alter_product_label_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('urgent', 'Urgent')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
